import { AlertTriangle, ArrowRight, CheckCircle2, ChevronLeft, Clock3, FileCheck2, Route, Truck } from "lucide-react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router-dom";
import { useState } from "react";
import { toast } from "sonner";
import { api, apiError, getData } from "../api/client.js";
import RouteMap from "../components/RouteMap.jsx";
import { EmptyState, ErrorState, InlineLoader, LoadingState, MetricCard, Modal, PageHeader, Progress, StatusBadge } from "../components/UI.jsx";
import { number } from "../utils/format.js";

function ShipmentTable({ shipments }) {
  return <div className="table-shell"><table className="desktop-table w-full text-left"><thead className="bg-cream text-xs uppercase tracking-wider text-gray-500"><tr>{["Shipment", "Orders", "Route", "Vehicle / fleet partner", "Distance", "Utilisation", "Status", ""].map((label) => <th key={label} className="px-5 py-4">{label}</th>)}</tr></thead><tbody className="divide-y">{shipments.map((shipment) => <tr key={shipment._id}><td data-label="Shipment" className="px-5 py-4 font-display font-bold">{shipment._id.toUpperCase()}</td><td data-label="Orders" className="px-5 py-4 text-sm">{shipment.orderIds.length}</td><td data-label="Route" className="px-5 py-4 text-sm"><p className="font-semibold">{shipment.stops[0]?.label}</p><p className="mt-1 max-w-48 truncate text-xs text-gray-500">to {shipment.stops.at(-1)?.label}</p></td><td data-label="Vehicle / fleet partner" className="px-5 py-4 text-sm"><p className="font-semibold">{shipment.vehicle?.split(" · ")[0]}</p><p className="text-xs text-gray-500">{shipment.fleetPartner}</p></td><td data-label="Distance" className="px-5 py-4 text-sm">{shipment.distance} km</td><td data-label="Utilisation" className="px-5 py-4"><div className="w-24"><Progress value={shipment.utilization} /></div></td><td data-label="Status" className="px-5 py-4"><StatusBadge status={shipment.status} /></td><td data-label="Action" className="px-5 py-4"><Link to={`/shipments/${shipment._id}`} className="btn-ghost">Track <ArrowRight className="h-4 w-4" /></Link></td></tr>)}</tbody></table></div>;
}

export function LogisticsDashboardPage() {
  const { data: shipments = [], isLoading } = useQuery({ queryKey: ["shipments"], queryFn: () => getData(api.get("/shipments")) });
  return <div className="container-page py-10"><PageHeader eyebrow="Operations control" title="Shipments" description="Monitor pickup readiness, route progress, delivery risk and proof states." actions={<Link to="/logistics/planner" className="btn-primary"><Route className="h-4 w-4" />Open route planner</Link>} /><div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Ready for pickup" value={shipments.filter((shipment) => shipment.status === "READY_FOR_PICKUP").length} icon={Truck} /><MetricCard label="In transit" value={shipments.filter((shipment) => shipment.status === "IN_TRANSIT").length} icon={Route} tone="blue" /><MetricCard label="Delivered today" value={shipments.filter((shipment) => shipment.status === "DELIVERED").length} icon={CheckCircle2} /><MetricCard label="Delayed" value={shipments.filter((shipment) => shipment.status === "DELAYED").length} icon={AlertTriangle} tone="amber" /></div>{isLoading ? <LoadingState /> : <ShipmentTable shipments={shipments} />}</div>;
}

export function LogisticsPlannerPage() {
  const [selected, setSelected] = useState(""); const queryClient = useQueryClient();
  const { data: bootstrap, isLoading } = useQuery({ queryKey: ["bootstrap"], queryFn: () => getData(api.get("/bootstrap")) });
  const shipments = bootstrap?.shipments || []; const current = shipments.find((shipment) => shipment._id === selected) || shipments.find((shipment) => shipment.status !== "DELIVERED");
  const optimize = useMutation({ mutationFn: (id) => getData(api.post(`/shipments/${id}/optimize`)), onSuccess: () => { toast.success("Route recomputed"); queryClient.invalidateQueries({ queryKey: ["bootstrap"] }); }, onError: (error) => toast.error(apiError(error)) });
  if (isLoading) return <LoadingState />;
  return <div className="container-page py-10"><PageHeader eyebrow="Fleet operations" title="Route planner" description="Review vehicle capacity, pickup order and delivery routes before dispatch." /><div className="grid gap-6 xl:grid-cols-[340px_1fr]"><aside className="card p-4"><h2 className="font-display text-lg font-bold">Shipments</h2><div className="mt-4 space-y-2">{shipments.filter((shipment) => shipment.status !== "DELIVERED").map((shipment) => <button key={shipment._id} onClick={() => setSelected(shipment._id)} className={`w-full rounded-2xl border p-4 text-left ${current?._id === shipment._id ? "border-forest-500 bg-forest-50" : "border-gray-200"}`}><div className="flex justify-between gap-2"><strong>{shipment._id.toUpperCase()}</strong><StatusBadge status={shipment.status} /></div><p className="mt-2 text-xs text-gray-500">{shipment.load}kg · {shipment.stops.length} stops</p></button>)}</div></aside><section>{current ? <div className="space-y-5"><div className="card overflow-hidden"><div className="flex items-center justify-between gap-4 p-5"><div><h2 className="font-display text-xl font-bold">{current._id.toUpperCase()}</h2><p className="mt-1 text-sm text-gray-500">{current.vehicle} · {current.fleetPartner}</p></div><button className="btn-primary" onClick={() => optimize.mutate(current._id)} disabled={optimize.isPending}>{optimize.isPending ? <InlineLoader /> : <><Route className="h-4 w-4" />Recompute</>}</button></div><RouteMap stops={current.stops} className="h-[480px] rounded-none border-0" /></div><div className="grid gap-4 sm:grid-cols-3"><MetricCard label="Load" value={`${number(current.load)}kg`} icon={Truck} /><MetricCard label="Capacity used" value={`${current.utilization}%`} icon={Route} tone="blue" /><MetricCard label="Estimated duration" value={`${current.duration} min`} icon={Clock3} tone="amber" /></div></div> : <EmptyState title="Choose a shipment" />}</section></div></div>;
}

export function ShipmentDetailsPage() {
  const { id } = useParams(); const queryClient = useQueryClient(); const [proof, setProof] = useState(null);
  const { data: shipment, isLoading, error } = useQuery({ queryKey: ["shipment", id], queryFn: () => getData(api.get(`/shipments/${id}`)) });
  const optimize = useMutation({ mutationFn: () => getData(api.post(`/shipments/${id}/optimize`)), onSuccess: () => { toast.success("Route recomputed"); queryClient.invalidateQueries({ queryKey: ["shipment", id] }); }, onError: (reason) => toast.error(apiError(reason)) });
  const submitProof = useMutation({ mutationFn: () => getData(api.post(`/shipments/${id}/${proof === "pickup" ? "proof-of-pickup" : "proof-of-delivery"}`, proof === "pickup" ? { receiverName: "Collection agent", quantity: shipment.load, notes: "Crates counted and sealed." } : { receiverName: "Buyer receiving desk", acceptedQuantity: shipment.load, rejectedQuantity: 0, notes: "Received in good condition." })), onSuccess: () => { toast.success(`Proof of ${proof} recorded`); setProof(null); queryClient.invalidateQueries({ queryKey: ["shipment", id] }); }, onError: (reason) => toast.error(apiError(reason)) });
  if (isLoading) return <div className="container-page py-10"><LoadingState cards={2} /></div>; if (error) return <div className="container-page py-10"><ErrorState /></div>;
  return <div className="container-page py-10"><Link to="/logistics" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-forest-700"><ChevronLeft className="h-4 w-4" />All shipments</Link><PageHeader eyebrow="Smart logistics" title={shipment._id.toUpperCase()} description={`${shipment.stops.length} route stops · ${shipment.orderIds.length} consolidated orders`} actions={<><StatusBadge status={shipment.status} /><button className="btn-secondary" onClick={() => optimize.mutate()}><Route className="h-4 w-4" />Recompute</button></>} /><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><RouteMap stops={shipment.stops} className="h-[500px]" /><section className="card p-6"><h2 className="font-display text-xl font-bold">Route stops</h2><div className="mt-6 space-y-4">{shipment.stops.map((stop, index) => <div className="flex gap-4" key={`${stop.label}-${index}`}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-forest-700 text-xs font-bold text-white">{index + 1}</span><div><p className="text-sm font-bold">{stop.label}</p><p className="mt-1 text-xs text-gray-500">{stop.type} · {stop.status?.replaceAll("_", " ")}</p></div></div>)}</div></section></div><aside className="space-y-5"><section className="card p-6"><h2 className="font-display text-lg font-bold">Vehicle & fleet partner</h2><div className="mt-4 rounded-2xl bg-cream p-4"><p className="font-bold">{shipment.vehicle}</p><p className="mt-2 text-sm text-gray-600">{shipment.fleetPartner}</p><p className="mt-1 text-xs font-bold text-forest-700">{shipment.phone || "Assigned contact protected"}</p></div><div className="mt-5"><Progress value={shipment.utilization} label={`${number(shipment.load)} / ${number(shipment.capacity)}kg capacity`} /></div></section><div className="grid grid-cols-2 gap-3"><button className="btn-secondary px-3" onClick={() => setProof("pickup")}><FileCheck2 className="h-4 w-4" />Pickup proof</button><button className="btn-primary px-3" onClick={() => setProof("delivery")}><FileCheck2 className="h-4 w-4" />Delivery proof</button></div></aside></div><Modal open={Boolean(proof)} onClose={() => setProof(null)} title={`Record proof of ${proof}`}><div className="space-y-4"><p className="text-sm text-gray-600">Record the hand-off confirmation for this fleet shipment.</p><button className="btn-primary w-full" onClick={() => submitProof.mutate()} disabled={submitProof.isPending}>{submitProof.isPending ? <InlineLoader /> : `Confirm ${proof}`}</button></div></Modal></div>;
}

export function AdminPage() {
  const { data: disputes = [], isLoading } = useQuery({ queryKey: ["disputes"], queryFn: () => getData(api.get("/disputes")) });
  return <div className="container-page py-10"><PageHeader eyebrow="Platform operations" title="Trust & dispute centre" description="Review marketplace exceptions with evidence and an audited resolution history." actions={<Link to="/admin/verifications" className="btn-primary">Open verification queue</Link>} />{isLoading ? <LoadingState /> : disputes.length ? <div className="grid gap-4">{disputes.map((dispute) => <article className="card p-5" key={dispute._id}><div className="flex items-center justify-between"><div><h2 className="font-display text-lg font-bold">{dispute.reason?.replaceAll("_", " ")}</h2><p className="mt-1 text-sm text-gray-500">Order {dispute.orderId}</p></div><StatusBadge status={dispute.status} /></div><p className="mt-4 text-sm text-gray-600">{dispute.description}</p></article>)}</div> : <EmptyState title="No active disputes" />}</div>;
}
