import { ArrowRight, CalendarDays, ChevronLeft, Clock3, MapPin, MessageSquareHeart, PackageCheck, ReceiptIndianRupee, Route, Split, Truck, UsersRound } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import { Link, useParams } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { api, getData } from '../api/client.js';
import { EmptyState, ErrorState, LoadingState, PageHeader, Progress, StatusBadge } from '../components/UI.jsx';
import RouteMap from '../components/RouteMap.jsx';
import { money, number, shortDate } from '../utils/format.js';
import SmartImage from '../components/SmartImage.jsx';

function OrderItem({ item }) {
  return <div className="flex min-w-0 items-center gap-3">
    {item.image ? <SmartImage src={item.image} alt="" className="h-12 w-12 shrink-0 rounded-xl object-cover"/> : <span className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-forest-50 text-forest-700"><PackageCheck className="h-5 w-5"/></span>}
    <div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.name}</p><p className="text-xs text-gray-500">{number(item.quantity)}{item.unit || 'kg'}{item.price ? ` × ${money(item.price)}` : ''}</p></div>
  </div>;
}

export function OrdersPage() {
  const { t } = useTranslation();
  const { data: orders = [], isLoading, error } = useQuery({ queryKey: ['orders'], queryFn: () => getData(api.get('/orders')), refetchInterval: 20_000 });
  return <div className="container-page py-10">
    <PageHeader eyebrow="Purchases" title="Your orders" description="Follow retail orders and multi-supplier bulk fulfillment from confirmation through delivery."/>
    {isLoading ? <LoadingState cards={3}/> : error ? <ErrorState message="Sign in to view your order history."/> : orders.length ? <div className="space-y-4">{orders.map((order) => <article key={order._id} className="card p-5 sm:p-6">
      <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-display text-lg font-bold">{order._id}</h2><StatusBadge status={order.status}/><span className="badge bg-gray-100 text-gray-600">{order.type}</span></div><div className="mt-2 flex flex-wrap gap-4 text-xs text-gray-500"><span><CalendarDays className="mr-1 inline h-3.5 w-3.5"/>Ordered {shortDate(order.createdAt)}</span><span><Truck className="mr-1 inline h-3.5 w-3.5"/>Expected {shortDate(order.deliveryDate)}</span>{order.splitSummary && <span><Split className="mr-1 inline h-3.5 w-3.5"/>{order.splitSummary.supplierCount} suppliers · {order.splitSummary.shipmentCount} trips</span>}</div></div><div className="flex items-center justify-between gap-6 sm:justify-end"><div className="text-right"><p className="text-xs text-gray-500">Order value</p><p className="font-display text-xl font-bold">{money(order.total)}</p></div>{order.status === 'DELIVERED' ? <Link to={`/orders/${order._id}/review`} className="btn-primary"><MessageSquareHeart className="h-4 w-4"/>{t('review.rateCta')}</Link> : <Link to={`/orders/${order._id}`} className="btn-primary">Track order <ArrowRight className="h-4 w-4"/></Link>}</div></div>
      <div className="mt-5 flex gap-3 overflow-auto border-t pt-5">{order.items?.map((item) => <div key={item.productId} className="min-w-56 rounded-2xl bg-cream p-3"><OrderItem item={item}/></div>)}</div>
    </article>)}</div> : <EmptyState title="No active orders" description="Your next farm-fresh delivery will appear here." action={<Link className="btn-primary" to="/marketplace">Shop produce</Link>}/>} 
  </div>;
}

function SplitFulfillment({ order }) {
  if (!order.suborders?.length) return null;
  return <section className="card p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="eyebrow mb-2">Automatic bulk split</p><h2 className="font-display text-xl font-bold">Supplier allocations</h2><p className="mt-2 text-sm text-gray-500">Inventory is reserved lot-by-lot and every capacity share is visible.</p></div><span className="badge bg-violet-50 text-violet-700"><UsersRound className="h-3.5 w-3.5"/>{order.suborders.length} supplier{order.suborders.length === 1 ? '' : 's'}</span></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2">{order.suborders.map((suborder) => <article key={suborder._id} className="rounded-2xl border border-gray-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{suborder.sellerName || suborder.sellerId}</p><p className="mt-1 text-xs text-gray-500">{suborder._id}</p></div><StatusBadge status={suborder.status}/></div><div className="mt-4 flex items-end justify-between"><div><p className="font-display text-2xl font-bold">{number(suborder.quantity)}{suborder.unit || 'kg'}</p><p className="mt-1 text-xs text-gray-500">{suborder.allocationPercent}% of requested volume</p></div><p className="text-sm font-bold">{money(suborder.subtotal)}</p></div><div className="mt-4"><Progress value={suborder.allocationPercent} label={`${suborder.lotAllocations?.length || 0} FEFO lots reserved`}/></div>{suborder.lotAllocations?.length > 0 && <div className="mt-3 flex flex-wrap gap-1.5">{suborder.lotAllocations.map((lot) => <span key={lot.lotId} className="badge bg-cream text-gray-600">{lot.lotCode} · {number(lot.quantity)}kg</span>)}</div>}</article>)}</div>
  </section>;
}

function ShipmentTrips({ shipments }) {
  if (!shipments?.length) return null;
  return <section className="card p-6"><div className="flex items-center justify-between"><div><p className="eyebrow mb-2">Split transport</p><h2 className="font-display text-xl font-bold">Fulfillment trips</h2></div><span className="badge bg-blue-50 text-blue-700"><Route className="h-3.5 w-3.5"/>{shipments.length} auto-planned</span></div><div className="mt-5 space-y-3">{shipments.map((shipment, index) => <div key={shipment._id} className="rounded-2xl bg-cream p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-bold">Trip {index + 1} · {shipment._id}</p><StatusBadge status={shipment.status}/></div><p className="mt-2 text-xs text-gray-500">{number(shipment.load)}kg · {shipment.stops.length} stops · {shipment.distance}km · {shipment.fleetPartner}</p><p className="mt-2 text-xs font-bold text-forest-700">{shipment.nextStop ? `Next: ${shipment.nextStop.label}` : shipment.status === 'DELIVERED' ? 'Delivered' : 'Dispatch pending'}</p>{shipment.liveLocation && <p className="mt-2 text-xs text-blue-700">Live GPS · {shipment.remainingDistance ?? shipment.distance}km remaining · ETA {shipment.estimatedArrival ? new Date(shipment.estimatedArrival).toLocaleTimeString() : 'calculating'}</p>}</div>)}</div></section>;
}

export function OrderDetailsPage() {
  const { id } = useParams();
  const { t } = useTranslation();
  const { data, isLoading, error } = useQuery({ queryKey: ['order', id], queryFn: () => getData(api.get(`/orders/${id}`)), refetchInterval: 15_000 });
  if (isLoading) return <div className="container-page py-12"><LoadingState cards={2}/></div>;
  if (error) return <div className="container-page py-12"><ErrorState message="We could not load this order."/></div>;
  const events = ['Order placed', 'Confirmed', 'Ready for pickup', 'Picked up', 'Collection center', 'Quality checked', 'In transit', 'Out for delivery', 'Delivered'];
  const active = data.status === 'DELIVERED' ? 8 : data.status === 'IN_TRANSIT' ? 6 : data.status === 'PICKED_UP' ? 3 : data.status === 'READY_FOR_PICKUP' ? 2 : 1;
  const bulk = String(data.type).startsWith('BULK');
  const storeExpress = data.type === 'STORE_EXPRESS';
  return <div className="container-page py-10"><Link to="/orders" className="mb-6 inline-flex items-center gap-2 text-sm font-bold text-forest-700"><ChevronLeft className="h-4 w-4"/>Back to orders</Link><PageHeader eyebrow={storeExpress ? 'Urban store express order' : bulk ? 'Bulk procurement order' : 'Retail order'} title={data._id} description={`Placed ${shortDate(data.createdAt)} · ${data.items?.length} product line${data.items?.length === 1 ? '' : 's'}${data.storeName ? ` · fulfilled by ${data.storeName}` : ''}${data.splitSummary ? ` · ${data.splitSummary.supplierCount} suppliers split automatically` : ''}`} actions={<StatusBadge status={data.status} className="px-4 py-2"/>}/>
    <div className="grid items-start gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><section className="card overflow-hidden"><div className="border-b border-gray-100 p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-gray-500">Current status</p><h2 className="mt-1 font-display text-2xl font-bold">{String(data.status).replaceAll('_', ' ')}</h2></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-forest-100 text-forest-700"><Truck className="h-5 w-5"/></div></div><p className="mt-3 text-sm text-gray-500">Estimated arrival: {shortDate(data.shipment?.estimatedArrival || data.deliveryDate || data.shipment?.eta)}. Delivery windows remain estimates.</p>{data.shipment?.liveLocation && <div className="mt-4 rounded-2xl bg-blue-50 p-4 text-xs text-blue-900"><strong>Live vehicle tracking</strong><p className="mt-1">Driver GPS updated {new Date(data.shipment.liveLocation.updatedAt).toLocaleTimeString()} · {data.shipment.remainingDistance ?? data.shipment.distance}km remaining · {data.shipment.remainingDuration ?? data.shipment.duration} minutes estimated.</p></div>}</div>{data.shipment?.stops ? <RouteMap stops={data.shipment.stops} liveLocation={data.shipment.liveLocation} className="h-[360px] rounded-none border-0"/> : <div className="grid h-52 place-items-center bg-forest-50 text-center"><div><PackageCheck className="mx-auto h-8 w-8 text-forest-600"/><p className="mt-3 font-bold">Shipment assignment pending</p><p className="mt-1 text-sm text-gray-500">Tracking appears after a vehicle is assigned.</p></div></div>}</section>
      <SplitFulfillment order={data}/><ShipmentTrips shipments={data.shipments}/><section className="card p-6"><h2 className="font-display text-xl font-bold">Journey timeline</h2><div className="mt-6 grid gap-0">{events.map((event, index) => <div key={event} className="flex gap-4"><div className="flex flex-col items-center"><span className={`grid h-7 w-7 place-items-center rounded-full border-2 ${index <= active ? 'border-forest-600 bg-forest-600 text-white' : 'border-gray-200 bg-white text-gray-300'}`}>{index <= active ? '✓' : ''}</span>{index < events.length - 1 && <span className={`h-9 w-0.5 ${index < active ? 'bg-forest-400' : 'bg-gray-200'}`}/>}</div><div className="pt-1"><p className={`text-sm font-bold ${index <= active ? 'text-ink' : 'text-gray-400'}`}>{event}</p>{index === active && <p className="mt-1 text-xs text-forest-600">Latest confirmed update</p>}</div></div>)}</div></section></div>
      <aside className="space-y-5"><section className="card p-6"><h2 className="font-display text-lg font-bold">Order summary</h2><div className="mt-5 space-y-4">{data.items?.map((item) => <OrderItem key={item.productId} item={item}/>)}</div><div className="mt-5 flex justify-between border-t pt-4 font-display text-xl font-bold"><span>Total</span><span>{money(data.total)}</span></div><p className="mt-2 text-xs text-gray-500">Payment: {data.paymentStatus?.replaceAll('_', ' ')}</p>{data.fulfillmentPlan && <div className="mt-4 rounded-2xl bg-violet-50 p-4 text-xs leading-5 text-violet-800"><strong>{data.fulfillmentPlan.coveragePercent}% fulfillment planned</strong><p className="mt-1">{data.fulfillmentPlan.method}</p></div>}</section>{data.shipment && <section className="card p-6"><h2 className="font-display text-lg font-bold">Lead trip</h2><div className="mt-4 rounded-2xl bg-cream p-4"><p className="font-bold">{data.shipment.driver}</p><p className="mt-1 text-xs text-gray-500">{data.shipment.vehicle}</p><p className="mt-3 text-xs font-bold text-forest-700">{data.shipment.phone}</p></div><div className="mt-4 grid grid-cols-2 gap-3"><div><Clock3 className="h-4 w-4 text-gray-400"/><p className="mt-2 text-xs text-gray-500">Est. duration</p><p className="text-sm font-bold">{data.shipment.duration} min</p></div><div><MapPin className="h-4 w-4 text-gray-400"/><p className="mt-2 text-xs text-gray-500">Est. distance</p><p className="text-sm font-bold">{data.shipment.distance}km</p></div></div></section>}{data.status === 'DELIVERED' && <section className="card border-forest-200 bg-forest-50/60 p-6"><h2 className="font-display text-lg font-bold">{t('review.asideTitle')}</h2><p className="mt-2 text-sm leading-6 text-gray-600">{t('review.asideBody')}</p><Link to={`/orders/${data._id}/review`} className="btn-primary mt-4 w-full"><MessageSquareHeart className="h-4 w-4"/>{t('review.rateCta')}</Link></section>}<button className="btn-secondary w-full"><ReceiptIndianRupee className="h-4 w-4"/>Invoice placeholder</button></aside></div>
  </div>;
}
