import {ArrowRight,Building2,CheckCircle2,LockKeyhole,MapPin,ShieldCheck,Tractor,UsersRound} from 'lucide-react';
import {Link} from 'react-router-dom';
import {PageHeader,VerifiedBadge} from '../components/UI.jsx';
import {useAppStore} from '../store/useAppStore.js';

export function ProfilePage(){const user=useAppStore(s=>s.user);return <div className="container-page max-w-5xl py-10"><PageHeader eyebrow="Account" title="Profile & preferences" description="Your trading role controls available actions; transaction behaviour still depends on each purchase."/><div className="grid gap-6 lg:grid-cols-[320px_1fr]"><aside className="card p-6 text-center"><span className="mx-auto grid h-20 w-20 place-items-center rounded-3xl bg-forest-900 font-display text-2xl font-bold text-white">{user?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)||'KB'}</span><h2 className="mt-4 font-display text-xl font-bold">{user?.name||'Kishan Bhaiya visitor'}</h2><p className="mt-1 text-sm capitalize text-gray-500">{user?.role?.replace('_',' ')||'Not signed in'}</p>{user?.verified&&<div className="mt-3"><VerifiedBadge/></div>}<button className="btn-secondary mt-6 w-full">Edit profile</button></aside><section className="card p-6 sm:p-8"><h2 className="font-display text-xl font-bold">Contact & business details</h2><dl className="mt-6 grid gap-6 sm:grid-cols-2">{[['Email',user?.email||'—'],['Phone',user?.phone||'—'],['Organization',user?.organization||'Individual account'],['Default location',user?.location||'Bhubaneswar'],['Business type',user?.role?.replace('_',' ')||'Visitor'],['GSTIN','22AAAAA0000A1Z5 · Demo placeholder']].map(([k,v])=><div key={k} className="rounded-2xl bg-cream p-4"><dt className="text-xs text-gray-500">{k}</dt><dd className="mt-1 text-sm font-bold">{v}</dd></div>)}</dl><div className="mt-7 rounded-2xl border border-forest-200 bg-forest-50 p-5"><ShieldCheck className="h-5 w-5 text-forest-700"/><h3 className="mt-2 font-bold">Privacy & verification</h3><p className="mt-2 text-sm leading-6 text-gray-600">Private contact details never appear on public QR traceability pages. Development identities and documents are fictional.</p></div></section></div></div>}

export function FarmersPage(){return <div className="container-page py-10"><PageHeader eyebrow="Producer network" title="Meet verified farmers & FPOs" description="Discover growers with visible operational histories, quality records and products in season."/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[['seller-1','Nayak Family Farm','Khordha','Farmer',Tractor,'214'],['seller-2','Utkal Harvest FPO','Cuttack','FPO',UsersRound,'487'],['seller-3','Maa Mangala Growers','Puri','FPO',Building2,'176'],['seller-4','Subarnarekha Farmer Collective','Balasore','FPO',UsersRound,'302'],['seller-5','Hirakud Organics','Sambalpur','Farmer',Tractor,'119'],['seller-6','Satyabadi Fresh Farms','Puri','Farmer',Tractor,'102']].map(([id,name,location,type,Icon,orders])=><article key={id} className="card card-hover p-6"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-forest-100 text-forest-700"><Icon className="h-6 w-6"/></span><h2 className="mt-5 font-display text-xl font-bold">{name}</h2><div className="mt-2"><VerifiedBadge/></div><p className="mt-4 text-sm text-gray-500"><MapPin className="mr-1 inline h-4 w-4"/>{location} · {type}</p><p className="mt-2 text-sm text-gray-500">{orders} completed orders · 94%+ fulfilment</p><Link to={`/sellers/${id}`} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-forest-700">View seller profile <ArrowRight className="h-4 w-4"/></Link></article>)}</div></div>}

export function PermissionDeniedPage(){return <div className="container-page grid min-h-[65vh] place-items-center py-16 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-3xl bg-amber-50 text-amber-700"><LockKeyhole className="h-7 w-7"/></span><h1 className="page-title mt-6">This workspace belongs to another role</h1><p className="mx-auto mt-3 max-w-lg leading-7 text-gray-600">Your account is safe, but it does not have permission for this action. Try the matching workspace or use a development demo account.</p><div className="mt-7 flex justify-center gap-3"><Link to="/" className="btn-secondary">Return home</Link><Link to="/login" className="btn-primary">Switch demo account</Link></div></div></div>}
export function NotFoundPage(){return <div className="container-page grid min-h-[65vh] place-items-center py-16 text-center"><div><p className="font-display text-8xl font-extrabold text-forest-100">404</p><h1 className="page-title mt-3">This path hasn’t been planted</h1><p className="mt-3 text-gray-600">The page may have moved or the link is incomplete.</p><Link to="/" className="btn-primary mt-7">Back to Kishan Bhaiya</Link></div></div>}
export function SimpleDashboardPage({type='payments'}){return <><PageHeader eyebrow="Producer workspace" title={type==='payments'?'Payments & settlements':'Seller orders'} description={type==='payments'?'Monitor buyer payment states and internal ledger actions.':'Track buyer commitments and prepare lots for fulfilment.'}/><div className="card p-8"><CheckCircle2 className="h-8 w-8 text-forest-600"/><h2 className="mt-4 font-display text-xl font-bold">All records are up to date</h2><p className="mt-2 max-w-xl text-sm leading-6 text-gray-600">Seller transaction records stay inside the producer workspace. Buyer order pages and marketplace checkout are available only to buyer accounts.</p><Link to="/seller/dashboard" className="btn-primary mt-6">Return to producer overview <ArrowRight className="h-4 w-4"/></Link></div></>}
