import { AlertCircle,Check,Inbox,LoaderCircle,ShieldCheck,WifiOff,X } from 'lucide-react';
import { cx } from '../utils/format.js';

const tones={
  FRESH:'bg-emerald-50 text-emerald-700 border-emerald-200',ACTIVE:'bg-emerald-50 text-emerald-700 border-emerald-200',ACCEPTED:'bg-emerald-50 text-emerald-700 border-emerald-200',APPROVED:'bg-emerald-50 text-emerald-700 border-emerald-200',DELIVERED:'bg-emerald-50 text-emerald-700 border-emerald-200',CONFIRMED:'bg-emerald-50 text-emerald-700 border-emerald-200',PAID:'bg-emerald-50 text-emerald-700 border-emerald-200',
  SELL_SOON:'bg-amber-50 text-amber-700 border-amber-200',PENDING:'bg-amber-50 text-amber-700 border-amber-200',URGENT:'bg-red-50 text-red-700 border-red-200',DELAYED:'bg-red-50 text-red-700 border-red-200',REJECTED:'bg-red-50 text-red-700 border-red-200',EXPIRED:'bg-gray-100 text-gray-600 border-gray-200',
  NEGOTIATING:'bg-violet-50 text-violet-700 border-violet-200',IN_TRANSIT:'bg-blue-50 text-blue-700 border-blue-200',PICKED_UP:'bg-blue-50 text-blue-700 border-blue-200',PLANNED:'bg-sky-50 text-sky-700 border-sky-200',OPEN:'bg-amber-50 text-amber-700 border-amber-200',UNDER_REVIEW:'bg-violet-50 text-violet-700 border-violet-200'
};
export function StatusBadge({status,className}){ const label=String(status||'Unknown').replaceAll('_',' '); return <span className={cx('badge border',tones[status]||'bg-gray-100 text-gray-700 border-gray-200',className)}>{label}</span>; }
export function VerifiedBadge({compact=false}){ return <span className="inline-flex items-center gap-1 text-xs font-bold text-forest-700"><ShieldCheck className="h-4 w-4 fill-forest-100"/>{compact?'Verified':'Verified producer'}</span>; }
export function MetricCard({label,value,detail,icon:Icon,tone='green'}){ const colors={green:'bg-forest-50 text-forest-700',amber:'bg-amber-50 text-amber-700',blue:'bg-blue-50 text-blue-700',violet:'bg-violet-50 text-violet-700'}; return <article className="card p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-gray-500">{label}</p><p className="mt-2 font-display text-2xl font-extrabold tracking-tight text-ink">{value}</p>{detail&&<p className="mt-1 text-xs text-gray-500">{detail}</p>}</div>{Icon&&<span className={cx('grid h-11 w-11 shrink-0 place-items-center rounded-2xl',colors[tone])}><Icon className="h-5 w-5"/></span>}</div></article>; }
export function PageHeader({eyebrow,title,description,actions}){return <header className="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="max-w-3xl">{eyebrow&&<p className="eyebrow mb-2">{eyebrow}</p>}<h1 className="page-title">{title}</h1>{description&&<p className="mt-3 max-w-2xl leading-7 text-gray-600">{description}</p>}</div>{actions&&<div className="flex shrink-0 flex-wrap gap-3">{actions}</div>}</header>;}
export function LoadingState({cards=4}){return <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4" aria-label="Loading"><span className="sr-only">Loading</span>{Array.from({length:cards},(_,i)=><div key={i} className="card overflow-hidden p-4"><div className="skeleton aspect-[4/3]"/><div className="skeleton mt-4 h-5 w-2/3"/><div className="skeleton mt-3 h-4 w-full"/><div className="skeleton mt-6 h-11 w-full"/></div>)}</div>}
export function InlineLoader({label='Working…'}){return <span className="inline-flex items-center gap-2"><LoaderCircle className="h-4 w-4 animate-spin"/>{label}</span>}
export function EmptyState({title='Nothing here yet',description='New activity will appear here.',action}){return <div className="card flex min-h-64 flex-col items-center justify-center p-8 text-center"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-forest-50 text-forest-700"><Inbox className="h-6 w-6"/></span><h3 className="mt-4 font-display text-lg font-bold">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-gray-500">{description}</p>{action&&<div className="mt-5">{action}</div>}</div>}
export function ErrorState({message='We could not load this section.',onRetry}){return <div className="card border-red-100 bg-red-50/50 p-6"><div className="flex items-center gap-3"><AlertCircle className="h-5 w-5 text-red-600"/><div><p className="font-bold text-red-900">Something needs attention</p><p className="mt-1 text-sm text-red-700">{message}</p></div>{onRetry&&<button className="btn-secondary ml-auto" onClick={onRetry}>Try again</button>}</div></div>}
export function OfflineBanner(){return <div className="bg-amber-400 px-4 py-2 text-center text-xs font-bold text-amber-950"><WifiOff className="mr-2 inline h-4 w-4"/>You’re offline. Safe drafts stay on this device; orders and payments wait for connection.</div>}
export function Progress({value,label}){const safe=Math.min(100,Math.max(0,value||0));return <div><div className="mb-2 flex justify-between text-xs font-semibold text-gray-600"><span>{label}</span><span>{safe}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-gray-100"><div className="h-full rounded-full bg-forest-500 transition-all" style={{width:`${safe}%`}}/></div></div>}
export function Modal({open,onClose,title,children,footer}){if(!open)return null;return <div className="fixed inset-0 z-[100] grid place-items-end bg-ink/45 p-0 backdrop-blur-sm sm:place-items-center sm:p-5" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose();}}><section role="dialog" aria-modal="true" className="max-h-[92vh] w-full overflow-auto rounded-t-3xl bg-white shadow-2xl sm:max-w-lg sm:rounded-3xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-gray-100 bg-white px-6 py-5"><h2 className="font-display text-xl font-bold">{title}</h2><button className="btn-ghost h-10 w-10 p-0" onClick={onClose} aria-label="Close"><X className="h-5 w-5"/></button></header><div className="p-6">{children}</div>{footer&&<footer className="sticky bottom-0 flex justify-end gap-3 border-t border-gray-100 bg-white p-5">{footer}</footer>}</section></div>}
export function CheckRow({children}){return <li className="flex items-start gap-2 text-sm leading-6 text-gray-600"><Check className="mt-1 h-4 w-4 shrink-0 text-forest-600"/>{children}</li>}
